name: test
on: [push]
jobs:
  run-anchor:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 20.9.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install 

      - uses: actions/checkout@v4
      - uses: metadaoproject/setup-anchor@v2.1
        with:
          anchor-version: '0.30.1'
          solana-cli-version: '1.18.18'
          node-version: '20.9.0'

      - run: yarn upgrade @coral-xyz/anchor@0.30.1

      - run: anchor build
        shell: bash
        
      # Start solana-test-validator on a different port
      - name: Start solana-test-validator
        run: |
          solana-test-validator --rpc-port 8900 &
          echo $! > solana-test-validator.pid

      # Ensure the validator is ready
      - name: Wait for solana-test-validator
        run: sleep 5 # Adjust this duration if needed

      # Run your tests
      - run: anchor test
        shell: bash

      # Stop the solana-test-validator
      - name: Stop solana-test-validator
        run: |
          kill $(cat solana-test-validator.pid) || true
          rm solana-test-validator.pid
