name: test

on: workflow_dispatch

jobs:
  build:
    name: Anchor Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3

      - uses: metadaoproject/setup-anchor@v2
        with:
          anchor-version: '0.30.1'
          solana-cli-version: '1.14.20'
          node-version: '16.15.1'

  test:
    name: Anchor Test
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: actions/checkout@v3

      - uses: metadaoproject/anchor-test@v2.1
        with:
          anchor-version: '0.30.1'
          solana-cli-version: '1.17.16'
