name: test
on: [push]
jobs:
  run-anchor:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: metadaoproject/setup-anchor@v2.1
        with:
          anchor-version: '0.30.1'
          solana-cli-version: '1.18.18'
          node-version: '20.9.0'
      - run: anchor build
        shell: bash
      - run: anchor test
        shell: bash

